# capitulo 3 - Matematica e Estastistica basica
#### Secão 1 -  Arrays e Numpy

In [4]:
import numpy as np 
from numpy.random import randn


In [6]:
#consifurando para ter apenas duas casas depois da virgula 
np.set_printoptions(precision=2)

##### Criando Arrays


In [19]:
a = np.array([1 ,2 ,3 ,4 ,5, 6])
a

array([1, 2, 3, 4, 5, 6])

In [20]:
#criando array por atribuição
np.random.seed(25)
b = randn(6)
b

array([ 0.23,  1.03, -0.84, -0.59, -0.96, -0.22])

In [21]:
c = np.arange(1, 20)
c

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [23]:
a + b 

array([1.23, 3.03, 2.16, 3.41, 4.04, 5.78])

In [27]:
a / b

array([  4.38,   1.95,  -3.57,  -6.77,  -5.23, -26.99])

## seção 2 - fazendo contas com matrizes 

In [40]:
a = np.arange(2, 5)
a

array([2, 3, 4])

In [53]:
aa = np.array([[1, 2, 3],[4 ,5 ,6],[7, 8, 9]])
aa

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [54]:
# Multiplicando nosso array pela nossa matriz de 3 linhas e 3 colunas
a * aa

array([[ 2,  6, 12],
       [ 8, 15, 24],
       [14, 24, 36]])

##### Multiplicando matriz por matriz 

In [68]:
bb = np.arange(9).reshape((3,3))
print(bb)
print("#__________#")
print(aa)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
#__________#
[[1 2 3]
 [4 5 6]
 [7 8 9]]


# Metodo para multiplicar matriz é np.dot

In [69]:
np.dot(bb, aa)

array([[ 18,  21,  24],
       [ 54,  66,  78],
       [ 90, 111, 132]])

# achando o valor escalar de dois arrays

In [74]:
b = a * 3
b

array([ 6,  9, 12])

In [75]:
np.dot(a, b)

87

# Estatisticas descritivas 
## dentro da estatistica descriviva temos dois tipos de descrição 
### A Obeservaçao e a disperção 
### etapa 3

## Essa é a lista de - Descriçao das observações de uma variavel 
#### * Soma 
#### * mediana 
#### * média 
#### * Maximo

## Essa é a lista de - Descriçao da dispersao de uma variavel 
#### * Desvio PAdrao
#### * variancia
#### * contagens
#### * Quartis

In [110]:
import pandas as pd
df = pd.read_csv("dados/mtcars.csv")
df.columns = ['nome', 'mpg', 'cyl', 'disp', 'hp', 'drat', 'wt', 'qsec', 'vs', 'am', 'gear', 
              'carb'] 
df.head(3)

nome   mpg  cyl   disp   hp  drat     wt   qsec  vs  am  gear  \
0      Mazda RX4  21.0    6  160.0  110  3.90  2.620  16.46   0   1     4   
1  Mazda RX4 Wag  21.0    6  160.0  110  3.90  2.875  17.02   0   1     4   
2     Datsun 710  22.8    4  108.0   93  3.85  2.320  18.61   1   1     4   

   carb  
0     4  
1     4  
2     1

## Descriçao das observações de uma variavel 


#### Soma

In [111]:
df.sum()df.sum()

SyntaxError: invalid syntax (<ipython-input-111-7f393d10aed4>, line 1)

In [112]:
# fazendo linha a linha 
# Porem se seu Data Frame for muito grande essa formar podera ser dificil de visualizar 
df.sum(axis=1)

0     328.980
1     329.795
2     259.580
3     426.135
4     590.310
5     385.540
6     656.920
7     270.980
8     299.570
9     350.460
10    349.660
11    510.740
12    511.500
13    509.850
14    728.560
15    726.644
16    725.695
17    213.850
18    195.165
19    206.955
20    273.775
21    519.650
22    506.085
23    646.280
24    631.175
25    208.215
26    272.570
27    273.683
28    670.690
29    379.590
30    694.710
31    288.890
dtype: float64

#### Mediana

In [113]:
df.median()

mpg      19.200
cyl       6.000
disp    196.300
hp      123.000
drat      3.695
wt        3.325
qsec     17.710
vs        0.000
am        0.000
gear      4.000
carb      2.000
dtype: float64

### media

In [114]:
df.mean()

mpg      20.090625
cyl       6.187500
disp    230.721875
hp      146.687500
drat      3.596563
wt        3.217250
qsec     17.848750
vs        0.437500
am        0.406250
gear      3.687500
carb      2.812500
dtype: float64

### maximo

In [115]:
df.max()

nome    Volvo 142E
mpg           33.9
cyl              8
disp           472
hp             335
drat          4.93
wt           5.424
qsec          22.9
vs               1
am               1
gear             5
carb             8
dtype: object

In [116]:
# podemos descobrir id maximo de uma determinada coluna
df['gear'].idxmax()

26

In [117]:
df.loc[20, 'gear']

3

# Descriçao da dispersao de uma variavel 

#### desvio padrao

In [118]:
df.std()

mpg       6.026948
cyl       1.785922
disp    123.938694
hp       68.562868
drat      0.534679
wt        0.978457
qsec      1.786943
vs        0.504016
am        0.498991
gear      0.737804
carb      1.615200
dtype: float64

#### variancia

In [120]:
df.var()

mpg        36.324103
cyl         3.189516
disp    15360.799829
hp       4700.866935
drat        0.285881
wt          0.957379
qsec        3.193166
vs          0.254032
am          0.248992
gear        0.544355
carb        2.608871
dtype: float64

### contagem de valores

In [129]:
df['cyl'].value_counts()

8    14
4    11
6     7
Name: cyl, dtype: int64

#### Descritivo estatistico

In [130]:
df.describe()

mpg        cyl        disp          hp       drat         wt  \
count  32.000000  32.000000   32.000000   32.000000  32.000000  32.000000   
mean   20.090625   6.187500  230.721875  146.687500   3.596563   3.217250   
std     6.026948   1.785922  123.938694   68.562868   0.534679   0.978457   
min    10.400000   4.000000   71.100000   52.000000   2.760000   1.513000   
25%    15.425000   4.000000  120.825000   96.500000   3.080000   2.581250   
50%    19.200000   6.000000  196.300000  123.000000   3.695000   3.325000   
75%    22.800000   8.000000  326.000000  180.000000   3.920000   3.610000   
max    33.900000   8.000000  472.000000  335.000000   4.930000   5.424000   

            qsec         vs         am       gear     carb  
count  32.000000  32.000000  32.000000  32.000000  32.0000  
mean   17.848750   0.437500   0.406250   3.687500   2.8125  
std     1.786943   0.504016   0.498991   0.737804   1.6152  
min    14.500000   0.000000   0.000000   3.000000   1.0000  
25%    16.892500   0.000000   0.000000   3.000000   2.0000  
50%    17.710000   0.000000   0.000000   4.000000   2.0000  
75%    18.900000   1.000000   1.000000   4.000000   4.0000  
max    22.900000   1.000000   1.000000   5.000000   8.0000